-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgiiEuhYosEeqNnX6t
BU6tqvo1s1lGPweAOYyUevjPqTOgCgYIKoZIzj0DAQehRANCAAS2h9dR3rmQ6iRt
rW8CC4ay9fLBGSRDv0Ptl6oAKbMGJbqkYcxOpR8zjSv3SE/dHaDWd/HK/3uqtb2i
TMJBpgHa
-----END PRIVATE KEY-----